server:
    port: 8080

spring:
    profiles: prod
    
    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://localhost:3306/bakendo_test
        #dataSourceClassName:  org.postgresql.ds.PGSimpleDataSource
        #url: jdbc:postgresql://localhost:5432/tineo3
        #url: jdbc:postgresql://ec2-54-225-156-230.compute-1.amazonaws.com:5432/d1a6pb5hov622m
        databaseName:
        serverName: 
        username: root
        password: 12077752
        #username: oelmxtdfujrqbw
        #password: ZAb69_zS0wX8JOm96dhJpIIZQl
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

    jpa:
        database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        database: MYSQL
        #database-platform: org.hibernate.dialect.PostgreSQLDialect
        #database: PostgreSQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
            

    mail:
        baseUrl: http://localhost:8080

    thymeleaf:
        mode: XHTML
        cache: true
        viewNames: error


metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 256M
